route:
  group_by: ['alertname', 'severity']

  group_wait: 30s
  # Only send the same alerts every 12h
  group_interval: 12h
  repeat_interval: 12h
  # We must deliver all alerts somewhere, so we use send them to a blackhole
  receiver: blackhole

  routes:
    # Sends configured alerts to discord
    - matchers:
        - alertname=~"KubePersistentVolumeFillingUp|KubeJobFailed|CPUThrottlingHigh"
      receiver: discord

# Prevert firing the same alerts with a lower level of severity
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match_re:
    severity: '(warning|critical)'
  equal: ['alertname', 'instance', 'job']
  
receivers:
- name: discord
  discord_configs:
  - webhook_url: <<discord_webhook_url>>
    message: '{{ template "our.discord.message" . }}'
    title: '{{ template "our.discord.title" . }}'

- name: blackhole
  

templates:
- '/etc/alertmanager/configmaps/default.tmpl/data'